(cl:defpackage ras_lab1_msgs-msg
  (:use )
  (:export
   "<PWM>"
   "PWM"
   "<CONTROLLERPARAMS>"
   "CONTROLLERPARAMS"
   "<ODOMETRY>"
   "ODOMETRY"
   "<WHEELANGULARVELOCITIES>"
   "WHEELANGULARVELOCITIES"
   "<ENCODERS>"
   "ENCODERS"
   "<SERVOMOTORS>"
   "SERVOMOTORS"
   "<BATTERYSTATUS>"
   "BATTERYSTATUS"
   "<ADCONVERTER>"
   "ADCONVERTER"
  ))

