(cl:defpackage phidgets-srv
  (:use )
  (:export
   "LIDAR_CONTROL"
   "<LIDAR_CONTROL-REQUEST>"
   "LIDAR_CONTROL-REQUEST"
   "<LIDAR_CONTROL-RESPONSE>"
   "LIDAR_CONTROL-RESPONSE"
   "INTERFACE_KIT"
   "<INTERFACE_KIT-REQUEST>"
   "INTERFACE_KIT-REQUEST"
   "<INTERFACE_KIT-RESPONSE>"
   "INTERFACE_KIT-RESPONSE"
  ))

