(cl:defpackage realsense_camera-srv
  (:use )
  (:export
   "FORCEPOWER"
   "<FORCEPOWER-REQUEST>"
   "FORCEPOWER-REQUEST"
   "<FORCEPOWER-RESPONSE>"
   "FORCEPOWER-RESPONSE"
   "SETPOWER"
   "<SETPOWER-REQUEST>"
   "SETPOWER-REQUEST"
   "<SETPOWER-RESPONSE>"
   "SETPOWER-RESPONSE"
   "ISPOWERED"
   "<ISPOWERED-REQUEST>"
   "ISPOWERED-REQUEST"
   "<ISPOWERED-RESPONSE>"
   "ISPOWERED-RESPONSE"
   "CAMERACONFIGURATION"
   "<CAMERACONFIGURATION-REQUEST>"
   "CAMERACONFIGURATION-REQUEST"
   "<CAMERACONFIGURATION-RESPONSE>"
   "CAMERACONFIGURATION-RESPONSE"
  ))

